language: php

cache:
  directories:
  - $HOME/.composer/cache
  
before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    
jobs:
    include:
        -   php: 7.1
            env: TYPE=linting
            script:
                - composer require --dev friendsofredaxo/linter
                - vendor/bin/rexlint
        -   php: 7.3
            env: TYPE=phpstan
            script:
                - composer require --dev phpstan/phpstan
                - vendor/bin/phpstan analyse
