package: minibar
version: '2.4.3'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/minibar

load: late
requires:
    redaxo: ^5.16.0-beta1
    php:
        version: '>=8.1'

default_config:
      compile: 1;
